baseURL = 'https://chunky.cooking/'
languageCode = 'en-us'
title = 'Chunky Cooking'
theme = 'lugo'

[params]
  favicon = "/favicon.ico"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true
  twitter = "makewithhugo"
  disqusShortname = "chunky-cooking"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
